### ISSUE TITLE
add timer

### ISSUE THREAD

**Issue by at15** [at15/med-crawler#1]
because 15s is limit for cloud code... i haven't thought about this at first... @arrowrowe  
( i used to think the sky is the limit)

**Comment by arrowrowe** [comment]
Fine. We don't mind a 1-hour interval in fact...

**Comment by at15** [comment]
i think it dose not matter even we set interval to 24h .... med won't have so many news.

**Comment by arrowrowe** [comment]
Should we close it now?

**Comment by at15** [comment]
@arrowrowe since we got the money (however I did not ... ), done
